export const ENDPOINTS = {
  HEALTH: '/health',
  REPORTS: '/reports',
  REPORT_BY_ID: (id: string) => `/reports/${id}`,
  VERIFY_REPORT: (id: string) => `/reports/${id}/verify`,
  TRANSITION_REPORT: (id: string) => `/reports/${id}/transition`,
  REPORT_STATS: '/reports/stats',
  REPORT_ASSIGN: (id: string) => `/reports/${id}/assign`,
  REPORT_ACKNOWLEDGE: (id: string) => `/reports/${id}/acknowledge`,
  REPORT_COMPLETE: (id: string) => `/reports/${id}/complete`,
  REPORT_DEPARTMENT_REJECT: (id: string) => `/reports/${id}/department-reject`,
  REPORT_ASSIGNMENTS: (id: string) => `/reports/${id}/assignments`,
  REPORT_AI_PROCESS: (id: string) => `/reports/${id}/ai/process`,
  REPORT_AI: (id: string) => `/reports/${id}/ai`,
  REPORT_AI_EVENTS: (id: string) => `/reports/${id}/ai/events`,
  AI_JOBS: '/ai/jobs',
  AI_METRICS: '/ai/metrics',
  AI_HEALTH: '/ai/health',
  DEPARTMENTS: '/departments',
  DEPARTMENT_BY_ID: (id: string) => `/departments/${id}`,
  DEPARTMENT_STATS: (id: string) => `/departments/${id}/stats`,
  DEPARTMENT_REPORTS: (id: string) => `/departments/${id}/reports`,
  ISSUES: '/issues',
  ISSUE_BY_ID: (id: string) => `/issues/${id}`,
  ISSUE_PRIORITY: (id: string) => `/issues/${id}/priority`,
  ISSUE_REPORTS: (id: string) => `/issues/${id}/reports`,
  MATCHES_PENDING: '/matches/pending',
  MATCH_APPROVE: (matchId: string) => `/matches/${matchId}/approve`,
  MATCH_REJECT: (matchId: string) => `/matches/${matchId}/reject`,
} as const;
